# TP 1 : Gestion des erreurs

Tout programme comporte des erreurs. 
C'est à cause de cette constatation que les développeurs essaient d'en réduire le nombre au maximum. 
Mais malgré cela, toutes les erreurs ne peuvent être prévisibles. Les erreurs syntaxiques sont interceptées lors de la compilation, 
mais il reste encore souvent des erreurs « imprévisibles ». 
Elles se produisent généralement de façon exceptionnelle, c'est-à-dire à la suite d'une action de l'utilisateur, 
ou de l'environnement. Une première solution pour palier ce problème consiste à mettre en place un système de code d'erreur. 
Cette technique rend difficile la lecture et l'écriture des programmes (imbrication de test conditionnel if...else...).

Java (comme beaucoup d'autres langages) propose un mécanisme de gestion d'exceptions, consistant à effectuer les instructions dans un bloc d'essai 
(le bloc try) qui surveille les instructions. Lors de l'apparition d'une erreur, celle-ci est lancée dans un bloc de traitement d'erreur 
(le bloc catch) sous forme d'un objet appelé Exception. Ce block catch peut alors traiter l'erreur ou la relancer vers un bloc de plus haut niveau. 
Un dernier block, finally, permet toujours d'exécuter une suite d'instructions qu'il y ait eu ou non exception. Il sert, par exemple, 
à ce qu'un fichier ouvert dans le bloc try soit systématiquement refermé, quoiqu'il arrive, grâce au bloc finally. 
Lorsque le programme rencontre une erreur dans un bloc try, 
une exception est instanciée puis lancée. L'interpréteur cherche un bloc catch à partir de l'endroit où l'exception a été créée. 
S'il ne trouve aucun bloc catch, l'exception est lancée dans le bloc de niveau supérieur et ainsi de suite jusqu'au bloc de la classe qui, 
par défaut, enverra l'exception à l'interpréteur. Celui-ci émettra alors un message d'alerte standard pour le type d'exception. 
Si un bloc catch est trouvé, celui-ci gérera l'exception et ne l'enverra pas à l'interpréteur.

Si par contre on désire que l'exception soit traitée par les blocs de niveaux supérieurs, 
il suffit d'inclure à la fin de la série d'instructions contenues dans le bloc catch une clause throw, 
suivie du type de l'exception entre parenthèse, puis du nom de l'exception. Ainsi l'exception continuera son chemin... 
Le mécanisme décrit ci-dessus, correspond aux exceptions contrôlées. 
Celles-ci doivent hériter de la classe java.lang.Exception. 
Par contre, les exceptions non contrôlées, comme leur non l'indique n'oblige pas le compilateur à exiger 
des blocks try/catch. Les exceptions non contrôlées (héritant de RuntimeException) peuvent ne pas être 
interceptées ou traitées.

```java
public class HelloPetstore {
    // Point d'entree de l'application
    public static void main(String[] args) {
        // si vous passez l'argument "controlee"
        if (args[0].equals("controlee")) {
            try {
                // Pour une exception controlee, vous etes obliges
                // de rattraper l'exception et de la traiter
                controlee();
                System.out.println("Ce texte ne s'affichera pas");
            } catch (Exception e) {
                System.out.println("Hello");
            } finally {
                System.out.println("PetStore!");
            }
            // Si vous passez l'argument noncontrolee
        } else {
            // Dans ce cas vous n'etes pas obliges de traiter l'exception
            noncontrolee();
            System.out.println("Ce texte ne s'affichera pas");
        }
    }
    // Une exception controlee doit apparaitre dans la signature
    private static void controlee() throws Exception {
        throw new Exception();
    }
    // Une exception non controlee n'apparait pas dans la signature
    private static void noncontrolee() {
        throw new RuntimeException();
    }
}
```

## Premier travail
Premier travail, lancer ce programme après l'avoir compilé en
essayant ```java HelloPetstore controlee``` et ```java HelloPetstore noncontrolee```

Vous pouvez récuper le code et un build gradle dans le gitgub
https://github.com/ISSAE/C1/tree/master/TPs/TP01/hello

Si vous avez déjà récupérer le git pour le TP0, n'oublier pas de faire
git pull! et vous trouverais ensiute l'exemple dans le repertoire TPs/TP01/hello

## Deuxième travail
Voir la L'analyse de besoin, spécification et conception du [produit V0 YAPS](petStore) (un petStore)
Bien s'en imprégner

Ensuite lancer les tests du projet TP01 (cette fois ci c'est du gradle pas maven...), corriger ou ajouter se qui manque pour que les tests unitaire fonctionnent

